path_classifiers:
  test:
    - fuzz
    - tests
    - unit-tests

extraction:
  cpp:
    prepare:
      packages:
        - lzip
        - libgpgme11-dev
    configure:
      command: ./bootstrap && ./configure --disable-doc
