sudo: no

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx

addons:
    apt:
        packages:
            - autoconf
            - automake
            - autopoint
            - libtool
            - gtk-doc-tools
            - gettext
            - flex
            - liblzma5
            - liblzma-dev
            - libidn2-0
            - libidn2-0-dev
            - libunistring0

# Change this to your needs
script: ./autogen.sh && ./configure --enable-gtk-doc && make -j4 && make check -j4 && make distcheck
before_install:
  - echo $TRAVIS_OS_NAME
  - ./.travis.sh
